### ISSUE TITLE
If question is retagged and even click once in editor then it says "edited" and not "retagged"

### ISSUE THREAD

**Issue by gurjyot** [q2a/question2answer#278]
If I have retagged a question but by mistake clicked even once in the editor (without making any changes, not even a space in changed) then after saving the question, it says the question is "edited" instead of "retagged". This should be corrected.

**Comment by svivian** [comment]
I can't reproduce this. Perhaps it was fixed by #276. If it shows up as "edited" instead of "retagged" then *something* must have changed in the text/html submitted.

**Comment by gurjyot** [comment]
I am updating the website, give me some days to investigate and then I'll let you know the final result.
But currently it is happening again and again, and I just noticed that even if I do not click in editor and just edit a tag or remove or write new one then this happens. So I am also not very much sure why and when it is is happening but is happening that I am sure of.

**Comment by gurjyot** [comment]
I am still facing this very problem. The source is still unknown to me, if I edit a tag, delete or remove a tag then sometimes it says that the question is edited instead of retagged. I think thorough testing is needed for this and I am trying to figure out what exactly is happening.

**Comment by svivian** [comment]
Going to close this as I have no way to reproduce it, therefore no way to fix it.

One possibility could be if you changed CKeditor settings (or when CKeditor was upgraded in Q2A) and you edited an old question, CKeditor may have automatically changed some of the HTML when it loaded (like removed obsolete tags), which would make it register as edited. If that's the case there isn't anything we can do about it.
