### ISSUE TITLE
Registration Form is not working. 

### ISSUE THREAD

**Issue by Jdweba** [q2a/question2answer#801]
HI, I have had this issue for a long time now but can't seem to get any help. 
I try to log into your QandA site but it wont send me an email verification. 

So anyway, the registration form on my site here just keeps returning back to the form every time someone try's to register. I have also tried myself with another email. 
Registered users can log in. 

I don't know about the Facebook log in but I think that's ok. 
I was told to disable captcha and I did but it made no difference. 

Here's the site : http://dv-eye.com/qtoa/
I have tweaked in admin but what ever I do it just doesn't work.
Any help appreciated. 

Thanks

**Comment by svivian** [comment]
Is this solved now? It looks like people are posting on your site.

**Comment by Jdweba** [comment]
No it's not fixed. I tried everything but just can't fix it. Not good with code in cpanel and changing things.

Be great if it was as zi really like the set up.

Any help appreciated

People just can't register.

Get BlueMail for Android<http://www.bluemail.me/r?b=15860>
On May 7, 2020, at 7:44 PM, Scott <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this solved now? It looks like people are posting on your site.

**Comment by svivian** [comment]
It's hard to know what to suggest. Try disabling all plugins and using one of the default themes without any modifications, as something could be interfering with the output.

You could also try checking the state of variables on the register page - `qa-include/pages/register.php`. For example before the last return line, try adding `var_dump($errors)` and see what is shown when you try to register.

**Comment by Jdweba** [comment]
OK I'll do that, thx.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
